baseURL = "https://embeddeddiary.github.io/"
title = "|EmbeddedDiary"
languageCode = "en-us"
paginate = 10
theme = "Binario"

[Params]
  description = "Hardware and Software blog"
  columns = 2
  dateFormat = "September 12, 2019"
